# Generated by Django 5.1.1 on 2025-10-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
