name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        pip install flake8 black isort
    
    - name: Check code formatting with black
      continue-on-error: true
      run: |
        black --check --diff api_yamdb/
    
    - name: Check import sorting with isort
      continue-on-error: true
      run: |
        isort --check-only --diff api_yamdb/
    
    - name: Run flake8
      continue-on-error: true
      run: |
        flake8 api_yamdb/ --count --show-source --statistics --max-line-length=88
